apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: project/helm/charts/project
    repoURL: https://github.com/toledompm/argocd-demo
    targetRevision: HEAD
    helm:
      releaseName: project-app
      valueFiles:
        - $values/custom-values.yaml
  - path: project/helm/charts/project
    repoURL: https://github.com/toledompm/argocd-demo
    targetRevision: HEAD
    helm:
      releaseName: project-app
      valueFiles:
        - $values/custom-values.yaml
  - repoURL: https://github.com/toledompm/argocd-demo
    targetRevision: HEAD
    ref: values
